LICENSE, MANIFEST.in, Makefile, dev_requirements.txt, pylintrc, pyoozie/__init__.py, pyoozie/builder.py, pyoozie/coordinator.py, pyoozie/tags.py, setup.cfg, setup.py, tests/__init__.py, tests/data/coordinator-with-controls.xml, tests/data/coordinator.xml, tests/data/workflow.xml, tests/pyoozie/__init__.py, tests/pyoozie/conftest.py, tests/pyoozie/test_builder.py, tests/pyoozie/test_coordinator.py, tests/pyoozie/test_package.py, tests/pyoozie/test_tags.py, tests/utils.py
This PR adds basic XML tag generation for Python 2 and 3 and a basic builder-interface that could be used to submit a simple workflow.
This PR leaves out:
- Documentation and a clear delineation of the public vs private APIs
- The actual Oozie API calls
https://github.com/Shopify/pyoozie/issues/3 documents non-implementation details that need to be fixed before releasing.
This PR should serve as a basis for adding Oozie API calls in a future PR.
review/ @honkfestival @kmtaylor-github
=> Add basic XML tag generation

pyoozie/builder.py, tests/pyoozie/test_builder.py
Oozie [workflow action names are identifiers](https://github.com/apache/oozie/blob/35db5b31fa0c69680de4fe12eabc6fde818b2c54/client/src/main/resources/oozie-workflow-0.5.xsd#L159), and identifiers must conform to [`([a-zA-Z_]([\-_a-zA-Z0-9])*){1,39}`](https://github.com/apache/oozie/blob/35db5b31fa0c69680de4fe12eabc6fde818b2c54/client/src/main/resources/oozie-workflow-0.5.xsd#L26). This PR adds this enforcement.
review/ @honkfestival @kmtaylor-github
=> Add validation on action names

.gitignore, .travis.yml, Makefile, tests/pyoozie/test_builder.py
This PR adds the ability to validate that the workflow XML that's generated against the [workflow XML schema](https://github.com/apache/oozie/blob/master/client/src/main/resources/oozie-workflow-0.5.xsd) using [`oozie validate`](https://oozie.apache.org/docs/4.1.0/DG_CommandLineTool.html#Validating_a_Workflow_XML) (for which the minimum set of binaries required are provided via `make install`).
Violations fail the test and if verbosity is turned on will print the XML that was tested and the validation error from the script, e.g.:
```
except subprocess.CalledProcessError as e:
raise AssertionError('An XML validation error\n\n{error}\n\noccurred while parsing:\n\n{xml}'.format(
error=e.output.decode('utf8').strip(),
>               xml=actual_xml,
))
E           AssertionError: An XML …
```
=> Add workflow XML validation to test

.travis.yml, Makefile, pylintrc, pyoozie/__init__.py, pyoozie/builder.py, pyoozie/client.py, pyoozie/coordinator.py, pyoozie/model.py, pyoozie/tags.py, setup.py, tests/pyoozie/test_builder.py, tests/pyoozie/test_client.py, tests/pyoozie/test_coordinator.py, tests/pyoozie/test_model.py, tests/pyoozie/test_tags.py
This PR:
- Adds the `shopify_python` linter plugin to pylint
- Fixes violations of the `import-modules-only` rule
- Disables the `global-variable` rule for now
Some of the changes to satisfy the `import-modules-only` rule look silly; those situations indicate  areas where we should maybe refactor, e.g. `coordinator.Coordinator` should perhaps be `xml.Coordinator`.
=> Add shopify_python linter and adhere to import-modules-only rule

pylintrc, pyoozie/client.py
Let's remove side-effects from importing `pyoozie.client` by removing the global logger var that's defined therein.
=> Make client logger per-instance to fix global-var lint rule

pylintrc, pyoozie/__init__.py, pyoozie/client.py, setup.py, tests/pyoozie/test_builder.py, tests/pyoozie/test_tags.py, tests/utils.py
This PR updates `shopify_python` from 0.1.2 to 0.2.0 and syncs `pylintrc` with `shopify_python` which brings with it a number of new linter rules checks. This PR also fixes lint errors by:
- Removing multiple imports on a line
- Moving a lot of code out of `try`'s
- Increasing the max except block size
=> Update shopify python to v0.2.0 and fix lint errors

pyoozie/__init__.py, pyoozie/builder.py, pyoozie/coordinator.py, pyoozie/tags.py, tests/pyoozie/test_tags.py
This PR renames and makes public two functions, `validate_xml_name` and `validate_xml_id`. These are useful for API users who are trying to create valid workflow/coordinator names (validated by `validate_xml_name`) or valid action names (validated by `validate_xml_id`).
Fixes https://github.com/Shopify/pyoozie/issues/18.
=> Make validate_id and validate_name public

pyoozie/__init__.py, pyoozie/tags.py, tests/pyoozie/test_tags.py
This PR changes how the `credential` tag is implemented to remove its pluralization because [`oozie-workflow-0.5.xsd`](https://github.com/apache/oozie/blob/master/client/src/main/resources/oozie-workflow-0.5.xsd) indicates that this tag shouldn't be pluralized:
```
<xs:complexType name="CREDENTIAL">
<xs:sequence  minOccurs="0" maxOccurs="unbounded" >
<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"/>
<xs:element name="value" minOccurs="1" maxOccurs="1" type="xs:string"/>
<xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="name" type="xs:string" use="required"/> …
```
=> Fix pluralization of credential tag

Makefile, pyoozie/model.py, setup.cfg, setup.py
This PR syncs up the `Makefile` with [shopify_python](https://github.com/Shopify/shopify_python) by adding the mypy and pep8 linters (and linting `setup.py`).
=> Add mypy and pep8 linters

pyoozie/model.py, tests/pyoozie/test_model.py
This PR fixes an issue where if a coordinator configuration contains a non-ASCII character then it fails to parse the configuration with the following exception in Python 2:
```
self = <xml.sax.expatreader.ExpatParser instance at 0x10bec5368>, data = '
<configuration>
<property>
<name>key1</name>
<value>value1</value>
</property>
<property>
<name>key2</name>
<value>😢</value>
</property>
</configuration>
', isFinal = 0
def feed(self, data, isFinal = 0):
if not self._parsing:
self.reset()
self._parsing = 1
self._cont_handler.startDocument()
try:
>           self._parser.Parse(data, isFinal)
E           UnicodeEncodeError: 'ascii' codec can't encode characters in position 160-161: ordinal not in range(128)
/usr/local/opt/pyenv/versions/2.7.13/lib/python2.7/xml/sax/expatreader.py:213: …
```
=> Read unicode coordinator configurations

Makefile, pyoozie/tags.py, pyoozie/xml.py, tests/data/workflow.xml, tests/pyoozie/test_client.py, tests/pyoozie/test_tags.py, tests/pyoozie/test_xml.py
This PR beings to add type hinting to pyoozie by:
- Adding a `make type` target to speed up testing; and
- Adds type annotations to `pyoozie.tags`.
During that, a return type change was made: XML output is returned as UTF-8 encoded bytes and not unicode strings. `pyoozie.client.jobs_submit_coordinator` and `pyoozie.client.jobs_submit_workflow`, which both XML output in HTTP POST bodies to Oozie were tested against Oozie 4.1.0 to ensure that they still submit data correctly (which uncovered an issue reading non-ASCII coordinator configurations shown in https://github.com/Shopify/pyoozie/pull/31).
=> Add types to pyoozie.tags

pyoozie/tags.py, tests/pyoozie/test_tags.py, tests/pyoozie/test_xml.py, tests/utils.py
This PR adds a basic `workflow-app` tag that simply contains a `start` and `end` with no other work and validates the XML that is generated from it.
An alias is not added to the `pyoozie` package and a warning is issued if it is used because it is not yet finished.
Subsequent PRs will add functionality discussed in https://github.com/Shopify/pyoozie/pull/26, including:
1. APIs to add a single action;
2. APIs to add an action on error (allowing us to remove `WorkflowBuilder`);
3. APIs to add multiple serial action (with actions on error); and then
4. APIs to add multiple parallel actions (with actions on error).
=> Add workflow tag

Makefile, setup.py
This is a [deprecated feature in pip](https://github.com/pypa/pip/blame/master/NEWS.rst#L690), so let's not rely upon it.
=> Remove dependency links

Makefile, setup.cfg, setup.py
[pep8 was renamed](http://pep8.readthedocs.io/en/release-1.7.x/) [pycodestyle](https://github.com/PyCQA/pycodestyle).
=> Replace pep8 with pycodestyle

setup.py
Seems like pylint>1.7 is causing the linter on master to fail with:
```
astroid.exceptions.AstroidImportError: Failed to import module pyoozie.xml.WorkflowBuilder with error:
No module named pyoozie.xml.WorkflowBuilder.
make: *** [sourcelint] Error 1
```
This PR pins pylint to have the same version ranges as [shopify_python](https://github.com/Shopify/shopify_python/blob/master/setup.py).
=> Pin Pylint in requirements

pyoozie/client.py, tests/pyoozie/test_client.py
This adds the ability to update a coordinator's definition without killing and recreating the coordinator.
According to the [docs]( https://oozie.apache.org/docs/4.1.0/DG_CommandLineTool.html#Updating_coordinator_definition_and_properties) a coordinator's definition can only be updated if the following are not changed:
- coordinator name
- frequency 
- start time
- end time
- timezone
If any of these are changed, then there should be a hard failure on the [request](https://github.com/Shopify/pyoozie/blob/master/pyoozie/client.py#L144).
I couldn't find anything specific on what coordinator states allow for an update so I assumed we would only want to update coordinators that are `active` or `running` or `suspended`. 
Curious if updating a coordinator in a `suspended` state makes sense. …
=> Add ability to update a coordinator's definition

pyoozie/model.py, tests/pyoozie/test_model.py
The `READY`/`WAITING` statuses for coordinator actions weren't tagged as being "active". 
Ditto for `PREP` on workflow actions.
@cfournie @sabidib
=> Add missing is_active tags to some statuses

pyoozie/model.py
The `fill_in_details()` mechanism relies on detecting that the `conf` field of `Coordinator` and `Workflow` objects was not provided (typical in bulk queries), and does a specific query to fetch the additional information. This change ensures that the parse function preserves `None`.
This is a bug introduced while getting lint to run clean; at one point parsing functions were skipped on null inputs, but the linter saw that as uninitialized variables.
@cfournie @sabidib
=> Leave conf None if not provided

tests/pyoozie/test_tags.py, tests/pyoozie/test_xml.py, tests/test_utils.py, tests/utils.py
This PR adds/changes utilities to make testing Oozie workflow XML a bit easier.  Specifically:
- `ParsedXml` will parse an XML string once using `ElementTree` and then allows users to assert using XPath that a single tag:
- Exists; or
- Has some specific attribute values
- `assert_valid_workflow` checks to make sure that duplicate names are not defined (and fixes an encoding issue)
These are used to test XML workflow generation in https://github.com/Shopify/pyoozie/pull/46.
=> Add test utilities

tests/test_utils.py, tests/utils.py
When testing https://github.com/Shopify/pyoozie/pull/46, sometimes XML comparisons would fail due to the ordering of lists of dicts (this happens maybe 10% of the time).
```
...
E             'fork': {'@name': 'fork-00000005',
E             -                            'path': [{'@start': 'action-00000000'},
E             ?                                                               ^
E             +                            'path': [{'@start': 'action-00000001'},
E             ?                                                               ^
E             -                                     {'@start': 'action-00000001'}]},
E             ?                                                               ^
E             +                                     {'@start': …
```
=> Fix flaky XML comparison

pyoozie/__init__.py, pyoozie/tags.py, setup.py, tests/pyoozie/test_interactive.py, tests/pyoozie/test_tags.py
This PR adds to the `WorkflowApp` class the ability to serialize to XML [action](https://oozie.apache.org/docs/4.1.0/WorkflowFunctionalSpec.html#a3.2_Workflow_Action_Nodes) and [kill](https://oozie.apache.org/docs/4.1.0/WorkflowFunctionalSpec.html#a3.1.3_Kill_Control_Node) nodes using the [`oozie-workflow-0.5.xsd` schema](https://github.com/apache/oozie/blob/master/client/src/main/resources/oozie-workflow-0.5.xsd).
This PR implements:
- An abstract `_WorkflowEntity` class to serve as the base type for these and other structures that will be exposed to users to allow them to define a workflow which features:
- An optional `on_error` parameter which allows one to specify a `_WorkflowEntity` to transition to if an error occurs
- An optional `name` to help document identifiers in the XML …
=> Add basic workflow generation

Makefile, pylintrc, setup.py
The latest version of setuptools (36.2.0) introduced https://github.com/pypa/setuptools/pull/1085, which disallows the manner in which we were specifying environment markers, which broke a variety of env marker usages https://github.com/pypa/setuptools/issues/1087.
This PR properly specifies env markers.
=> Change how we specify environment markers

pyoozie/__init__.py
Let's cut a feature release that includes these feature-adding PRs:
- Add ability to update a coordinator's definition https://github.com/Shopify/pyoozie/pull/42
- Add missing is_active tags to some statuses https://github.com/Shopify/pyoozie/pull/44
- Leave conf None if not provided https://github.com/Shopify/pyoozie/pull/47
- Add test utilities https://github.com/Shopify/pyoozie/pull/45
- Add basic workflow generation https://github.com/Shopify/pyoozie/pull/49
And the following bugfixes:
- Change how we specify environment markers https://github.com/Shopify/pyoozie/pull/53
This also includes other cleanup PRs including:
- Replace pep8 with pycodestyle https://github.com/Shopify/pyoozie/pull/39
- Pin Pylint in requirements https://github.com/Shopify/pyoozie/pull/43
- Fix flaky XML …
=> Increase version number to 0.0.1

Makefile, RELEASING.md
Based upon [`shopify_python`](https://github.com/Shopify/shopify_python)'s [`RELEASING.md`](https://github.com/Shopify/shopify_python/blob/master/RELEASING.md) and [`Makefile`](https://github.com/Shopify/shopify_python/blob/master/Makefile).
=> Add release instructions

pyoozie/__init__.py, pyoozie/client.py, tests/pyoozie/test_client.py
Added a public suspended coordinators api, needed for: https://github.com/Shopify/dogpound/pull/50
=> Suspended coordinators api

Makefile, RELEASING.md, setup.py
The release instructions assume that you have twine installed to deploy packages, but that may not be the case. This PR adds twine to the required libraries and changes the instructions to encourage their installation prior to usage.
=> Add twine to a user's env and talk about releasing from master

pyoozie/__init__.py, pyoozie/client.py, tests/pyoozie/test_client.py
Added `job_coordinator_rerun` which allows us to run the `coord-rerun` action on a coordinator action. Necessary for replicating the logic found here: https://github.com/Shopify/starscream/blob/master/starscream/scheduling/oozie/oozie_utils.py#L114-L125
I've also moved around and renamed `jobs_update_coordinator` since it didn't seem to follow the same pattern as the other functions.
AFAICT, functions starting with `jobs_*` hit the `/jobs` endpoint whereas functions starting with `job_*` hit the `/job` endpoint. Also the action name is typically the suffix of the function name.
=> Add job_coordinator_rerun

pyoozie/__init__.py, pyoozie/tags.py, tests/pyoozie/test_tags.py
This PR extends the available collections for Oozie workflow actions to include [`decision` nodes](https://oozie.apache.org/docs/4.1.0/WorkflowFunctionalSpec.html#a3.1.4_Decision_Control_Node) (using the [`oozie-workflow-0.5.xsd` schema](https://github.com/apache/oozie/blob/master/client/src/main/resources/oozie-workflow-0.5.xsd)) with error handling definable using an `on_error` parameter.
This PR implements decision nodes and error handling such that we can accomplish one crucial execution pattern: checkpointing.
When a collection of actions are being executed in parallel and one of them transitions to a kill node, that kills the entire workflow (parallel actions and all). The other parallel actions may complete successfully, but if a single one transitions to kill it interrupts them.
| …
=> Add decision action

pyoozie/client.py, setup.py, tests/pyoozie/test_client.py
The `OozieClient` constructor is performing a connection check. 
This can make testing harder than it should be.
- Add an argument to disable the check in the constructor
- Make the `test_connection` method part of the API
Resolves #63
=> Delay the connection check until the first request

pyoozie/model.py, pyoozie/tags.py, setup.py
`master` has been failing for a while with type errors.  This attempts to fix them.
https://travis-ci.org/Shopify/pyoozie/jobs/380235270#L971-L1034
Also mypy stopped supporting python 3.4 [about two weeks ago](https://github.com/python/mypy/pull/6592).
=> Fix CI errors on master

pyoozie/client.py, tests/pyoozie/test_client.py
Surface the `details` flag to avoid making additional REST calls (1 per item in the list) when the extra details are not necessary.
=> Allow specifying details flag to avoid extra REST calls

pyoozie/client.py, pyoozie/model.py, tests/pyoozie/test_model.py
Adds a `client_url` property to each model.
This makes it easier to use pyoozie models in an environment that has multiple oozie deployements.
=> Surface the client URL used to obtain a model

pyoozie/client.py, tests/pyoozie/test_client.py
This PR adds a requests.Session() object to OozieClient and replaces the requests convenience methods with the session. This allows OozieClient to pool connections and make more effective use of server resources. 
This will also allow users to pass in their own customized sessions if required.
=> Replace requests convenience methods with session object 

Makefile, setup.py
From Python 3.4 upwards, enum is built into the Python library. Installing enum34 in Python 3.4 upwards leads to issues where [`pip` gets broken](https://stackoverflow.com/a/45716067).
This PR does the following:
- properly gates the enum34 dependency such that it is only installed in versions of python < 3.4.
- updates the maven urls for `oozie-client` as well as `commons-cli`, as the previous URLs were broken.
- Finally, pins some packages for `mypy` type checking to pass
=> Gate enum34 requirement to python_version < 3.4

setup.py
The `typing` module was introduced natively with Python 3.5.  This change skip installing it via PIP if the version of Python >= 3.5.
This was causing problems when installing `pyoozie` from another project running Python 3.7.3:
```
File "/artifacts/virtualenv/python3/lib/python3.7/site-packages/foo/__init__.py", line 1, in <module>
import typing
File "/artifacts/virtualenv/python3/lib/python3.7/site-packages/typing.py", line 1357, in <module>
class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
File "/artifacts/virtualenv/python3/lib/python3.7/site-packages/typing.py", line 1005, in __new__
self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```
=> Use Python's typing package if available
